server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      # service registry에 있는 서비스명으로 라우팅처리
      # /service-1/** -> service-1물리주소/**
      # https://stackoverflow.com/questions/58714918/spring-cloud-gateway-auto-routing-with-eureka
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: "*"


---
spring:
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://ec2-15-165-88-135.ap-northeast-2.compute.amazonaws.com:8761/eureka/
  instance:
    hostname: ec2-15-165-88-135.ap-northeast-2.compute.amazonaws.com