spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-1.c31ujhjy02ba.ap-northeast-2.rds.amazonaws.com:5432/postgres?currentSchema=myworkspace
    username: postgre
    password: password123!
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: true
  cache:
    type: redis
    
  redis:
    host: 127.0.0.1
    port: 6379